import { boundedFeedbackValue, clamp, finiteArray, lifecycleStressCheck, PHOSPHOR_FAMILY_CATALOG, reactionDiffusionStep, seededRandom, stepElementary } from './core.mjs';

const $ = (id) => document.getElementById(id);
const canvas = $('stage');
const ctx = canvas.getContext('2d', { alpha: false });
const sceneList = $('sceneList');
const controls = $('sceneControls');
const cueList = $('cueList');
const toast = $('toast');

const sceneDefs = [
  { id: 'acid', number: '47', name: 'Acid Mycelium', tagline: 'Fluorescent reaction–diffusion structures that feel grown.', description: 'Slow branching veins with a luminous center.', kind: 'reaction', presets: [
    ['Mycelial City', 'dense branching streets', 18], ['Vein Cathedral', 'arched membranes', 41], ['Lime Bloom', 'soft radial growth', 73], ['Night Orchard', 'quiet clustered spores', 101], ['Tidal Membrane', 'wide liquid folds', 149], ['Signal Understory', 'fine electric filaments', 211],
  ], schema: [['growth', 'Growth', 0, 1, .01], ['injection', 'Injection', 0, 1, .01], ['diffusion', 'Diffusion', .2, 1.4, .01], ['contrast', 'Contrast', .5, 2, .01], ['drift', 'Drift', 0, 1, .01]] },
  { id: 'tapestry', number: '51', name: 'Causal Tapestry', tagline: 'Cellular histories become woven curtains.', description: 'A reversible scroll through a living history buffer.', kind: 'automaton', presets: [
    ['Nested Orchard', 'rule 90 · nested', 90], ['Periodic Loom', 'rule 54 · periodic', 54], ['Chaos Mantle', 'rule 30 · chaotic', 30], ['Quiet Weave', 'rule 184 · drifting', 184], ['Crown Pattern', 'rule 110 · complex', 110], ['Mirror Canal', 'rule 150 · braided', 150], ['Pulse Brocade', 'rule 22 · granular', 22], ['Night Relay', 'rule 126 · cellular', 126],
  ], schema: [['rule', 'Rule', 0, 255, 1], ['scroll', 'Scroll', 0, 1, .01], ['weave', 'Weave', 0, 1, .01], ['reversal', 'History playback', 0, 1, .01], ['phrase', 'Phrase length', 2, 16, 1]] },
  { id: 'feedback', number: '52', name: 'Feedback Chapel', tagline: 'Molten halos retain and dissolve traces of movement.', description: 'A mirrored tunnel that remembers the last gesture.', kind: 'feedback', presets: [
    ['Molten Halo', 'soft circular persistence', 13], ['Mirror Nave', 'four-fold architecture', 29], ['Glass Tunnel', 'deep receding trace', 47], ['Afterimage Choir', 'layered gesture memory', 71], ['Red Chapel', 'slow ember geometry', 113], ['Clean Recovery', 'bright opening / clear exit', 167],
  ], schema: [['decay', 'Decay', .72, .99, .005], ['transform', 'Transform', -.06, .06, .001], ['symmetry', 'Symmetry', 1, 6, 1], ['injection', 'Impulse', 0, 1, .01], ['tunnel', 'Tunnel depth', 0, 1, .01]] },
];

const initialParams = {
  acid: { growth: .62, injection: .34, diffusion: .82, contrast: 1.2, drift: .25 },
  tapestry: { rule: 90, scroll: .42, weave: .55, reversal: 0, phrase: 8 },
  feedback: { decay: .91, transform: .012, symmetry: 4, injection: .55, tunnel: .58 },
};
const palette = { primary: '#d5ff5f', secondary: '#5364ff', accent: '#ff5bc8' };
const state = { sceneIndex: 0, presetIndex: [0, 0, 0], params: structuredClone(initialParams), tempo: 92, paused: false, muted: false, blackout: false, reducedMotion: false, brightness: .92, quality: '1080', currentCue: -1, transition: null, dirty: false, setPlaying: false, lastTime: performance.now(), elapsed: 0, audioLevel: 0, gesture: { x: .5, y: .5, active: false }, demoOn: false };
const metrics = { frameTimes: [], sceneFrames: [0, 0, 0], reset() { this.frameTimes.length = 0; this.sceneFrames = [0, 0, 0]; } };

const buffers = {
  acid: { width: 120, height: 75, u: new Float32Array(120 * 75), v: new Float32Array(120 * 75), seed: 1, random: hash(1) },
  tapestry: { width: 220, height: 120, rows: Array.from({ length: 120 }, () => new Uint8Array(220)), current: new Uint8Array(220), cursor: 0, seed: 1 },
  feedback: { a: document.createElement('canvas'), b: document.createElement('canvas'), current: 0 },
};
buffers.feedback.a.width = buffers.feedback.b.width = canvas.width;
buffers.feedback.a.height = buffers.feedback.b.height = canvas.height;
const fctx = [buffers.feedback.a.getContext('2d'), buffers.feedback.b.getContext('2d')];
const renderBuffer = document.createElement('canvas'); renderBuffer.width = canvas.width; renderBuffer.height = canvas.height;
const renderCtx = renderBuffer.getContext('2d');
const transitionCanvas = document.createElement('canvas'); transitionCanvas.width = canvas.width; transitionCanvas.height = canvas.height;
const transitionCtx = transitionCanvas.getContext('2d');

let audio = { context: null, analyser: null, gain: null, recordDestination: null, source: null, demoGain: null, media: null, mediaUrl: null, micStream: null, data: null, recorder: null, recordingStream: null, recordingMime: null, chunks: [] };
let cueTimer = null;
let toastTimer = null;

function hash(seed) { return seededRandom(seed); }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.remove('show'), 2400); }
function scene() { return sceneDefs[state.sceneIndex]; }
function preset() { return scene().presets[state.presetIndex[state.sceneIndex]]; }
function markDirty() { state.dirty = true; $('dirtyState').textContent = 'UNSAVED'; scheduleSave(); }
function announce() { $('sceneKicker').textContent = `${scene().number} / ${scene().name}`; $('scenePresetName').textContent = preset()[0]; $('sceneDescription').textContent = scene().description; $('controlHeading').textContent = `${scene().name.toUpperCase()} / PARAMETERS`; $('transitionBadge').textContent = state.transition ? 'MORPHING' : 'LIVE'; $('tempoReadout').textContent = `♩ ${state.tempo} BPM`; $('tempoOutput').textContent = state.tempo; $('tempoReadout').setAttribute('aria-label', `${state.tempo} beats per minute`); $('qualityBadge').textContent = `${state.quality} / ${state.quality === '720' ? '30' : '60'}`; }
function colorRgb(hex) { const clean = hex.replace('#', ''); return [parseInt(clean.slice(0, 2), 16), parseInt(clean.slice(2, 4), 16), parseInt(clean.slice(4, 6), 16)]; }
function mixColor(a, b, amount) { const t = clamp(amount, 0, 1); return [Math.round(a[0] + (b[0] - a[0]) * t), Math.round(a[1] + (b[1] - a[1]) * t), Math.round(a[2] + (b[2] - a[2]) * t)]; }
function fillPalette() { document.documentElement.style.setProperty('--acid', palette.primary); document.documentElement.style.setProperty('--blue', palette.secondary); document.documentElement.style.setProperty('--pink', palette.accent); }

function resetAcid(seed = preset()[2]) {
  const b = buffers.acid; b.seed = seed; const rand = hash(seed); b.random = hash(seed ^ 0x51ac1d); b.u.fill(1); b.v.fill(0);
  for (let i = 0; i < b.v.length; i += 1) { if (rand() > .965) b.v[i] = rand() * .9; }
  for (let y = 0; y < 5; y += 1) for (let x = 0; x < 5; x += 1) { const i = (Math.floor(b.height / 2) + y - 2) * b.width + Math.floor(b.width / 2) + x - 2; b.v[i] = .9; }
}
function resetTapestry(seed = preset()[2]) { const b = buffers.tapestry; b.seed = seed; b.cursor = 0; b.current.fill(0); b.rows.forEach((row) => row.fill(0)); const rand = hash(seed); for (let i = 0; i < b.current.length; i += 1) b.current[i] = rand() > .84 ? 1 : 0; b.current[Math.floor(b.width / 2)] = 1; }
function resetFeedback() { buffers.feedback.current = 0; fctx[0].clearRect(0, 0, canvas.width, canvas.height); fctx[1].clearRect(0, 0, canvas.width, canvas.height); }
function resetScene() { if (scene().kind === 'reaction') resetAcid(); if (scene().kind === 'automaton') resetTapestry(); if (scene().kind === 'feedback') resetFeedback(); state.elapsed = 0; announce(); showToast('Seed reset · deterministic start restored'); markDirty(); }

function renderScenes() {
  sceneList.innerHTML = sceneDefs.map((item, i) => `<button class="scene-item ${i === state.sceneIndex ? 'active' : ''}" data-scene="${i}" aria-pressed="${i === state.sceneIndex}"><span class="scene-index">${item.number}</span><span class="scene-name">${item.name}</span><span class="scene-status"></span></button>`).join('');
  sceneList.querySelectorAll('[data-scene]').forEach((button) => button.addEventListener('click', () => switchScene(Number(button.dataset.scene))));
}
function renderControls() { const def = scene(); const values = state.params[def.id]; controls.innerHTML = def.schema.map(([key, label, min, max, step]) => `<div class="control"><label for="control-${key}">${label}<output id="output-${key}">${Number(values[key]).toFixed(step < 1 ? 2 : 0)}</output></label><input id="control-${key}" type="range" min="${min}" max="${max}" step="${step}" value="${values[key]}" /></div>`).join(''); def.schema.forEach(([key]) => { const input = $(`control-${key}`); input.addEventListener('input', () => { state.params[def.id][key] = Number(input.value); $(`output-${key}`).value = Number(input.value).toFixed(input.step < 1 ? 2 : 0); markDirty(); }); }); renderPresets(); }
function renderPresets() { const strip = $('presetStrip'); strip.innerHTML = scene().presets.map((item, i) => `<button class="preset-chip ${i === state.presetIndex[state.sceneIndex] ? 'active' : ''}" data-preset="${i}"><strong>${item[0]}</strong><small>${item[1]}</small></button>`).join(''); strip.querySelectorAll('[data-preset]').forEach((button) => button.addEventListener('click', () => selectPreset(Number(button.dataset.preset)))); }
function renderCues() { $('cueCount').textContent = `${cues.length.toString().padStart(2, '0')} CUES`; cueList.innerHTML = cues.map((cue, i) => `<div class="cue ${i === state.currentCue ? 'current' : ''}"><span class="cue-num">${String(i + 1).padStart(2, '0')}</span><div class="cue-main"><span class="cue-title">${cue.label}</span><span class="cue-meta">${sceneDefs[cue.scene].number} / ${sceneDefs[cue.scene].name} · ${cue.duration} bars</span></div><button class="cue-remove" data-remove-cue="${i}" aria-label="Remove ${cue.label}">×</button></div>`).join(''); cueList.querySelectorAll('[data-remove-cue]').forEach((button) => button.addEventListener('click', () => { if (cues.length <= 1) return showToast('A set needs at least one cue'); cues.splice(Number(button.dataset.removeCue), 1); state.currentCue = -1; renderCues(); markDirty(); })); }
const cues = [
  { label: 'Root / City breathing', scene: 0, preset: 0, duration: 8 }, { label: 'Causal bloom', scene: 1, preset: 2, duration: 12 }, { label: 'Glass remembers', scene: 2, preset: 2, duration: 16 }, { label: 'Clean recovery', scene: 2, preset: 5, duration: 8 },
];

function switchScene(index, presetIndex = state.presetIndex[index]) { if (index === state.sceneIndex && presetIndex === state.presetIndex[index]) return; transitionCtx.clearRect(0, 0, canvas.width, canvas.height); transitionCtx.drawImage(canvas, 0, 0); state.transition = { from: state.sceneIndex, to: index, progress: 0 }; state.sceneIndex = index; state.presetIndex[index] = clamp(presetIndex, 0, sceneDefs[index].presets.length - 1); if (scene().kind === 'reaction') resetAcid(); if (scene().kind === 'automaton') resetTapestry(); if (scene().kind === 'feedback') resetFeedback(); renderScenes(); renderControls(); announce(); markDirty(); }
function selectPreset(index) { state.presetIndex[state.sceneIndex] = clamp(index, 0, scene().presets.length - 1); resetScene(); renderPresets(); }

function inject(x = state.gesture.x, y = state.gesture.y, amount = 1) { const def = scene(); if (def.kind === 'reaction') { const b = buffers.acid; const cx = Math.floor(clamp(x, 0, 1) * b.width); const cy = Math.floor(clamp(y, 0, 1) * b.height); const radius = Math.max(2, Math.floor(2 + state.params.acid.injection * 6)); for (let yy = -radius; yy <= radius; yy += 1) for (let xx = -radius; xx <= radius; xx += 1) if (xx * xx + yy * yy <= radius * radius) { const i = ((cy + yy + b.height) % b.height) * b.width + ((cx + xx + b.width) % b.width); b.v[i] = clamp(b.v[i] + .7 * amount, 0, 1); b.u[i] = clamp(b.u[i] - .25 * amount, 0, 1); } } else if (def.kind === 'automaton') { const b = buffers.tapestry; b.current[Math.floor(clamp(x, 0, 1) * b.width)] = 1; } else { state.gesture = { x, y, active: true }; } }

function stepAcid(dt) { const p = state.params.acid; const b = buffers.acid; const speed = state.reducedMotion ? .35 : .7 + p.growth * 2.4; const steps = Math.max(1, Math.min(4, Math.floor(dt * 60 * speed / 16))); for (let i = 0; i < steps; i += 1) { const next = reactionDiffusionStep(b.u, b.v, b.width, b.height, .018 + p.growth * .026, .045 + (1 - p.growth) * .02, p.diffusion); b.u = next.u; b.v = next.v; } if (p.injection > .01 && b.random() < dt * 0.35) inject(.45 + Math.sin(state.elapsed * .3) * .22, .5 + Math.cos(state.elapsed * .23) * .2, p.injection * .25); }
function drawAcid() { const b = buffers.acid; const p = state.params.acid; const a = colorRgb(palette.primary); const s = colorRgb(palette.secondary); const c = colorRgb(palette.accent); const image = ctx.createImageData(b.width, b.height); for (let i = 0; i < b.v.length; i += 1) { let value = clamp(b.v[i] * p.contrast * 2.6, 0, 1); const m = value < .5 ? mixColor([5, 7, 12], s, value * 2) : mixColor(s, a, (value - .5) * 2); const tint = (Math.sin(i * .021 + state.elapsed * p.drift * 1.5) + 1) * .5; const rgb = mixColor(m, c, tint * value * .28); image.data[i * 4] = rgb[0]; image.data[i * 4 + 1] = rgb[1]; image.data[i * 4 + 2] = rgb[2]; image.data[i * 4 + 3] = 255; } renderBuffer.width = b.width; renderBuffer.height = b.height; renderCtx.putImageData(image, 0, 0); ctx.imageSmoothingEnabled = true; ctx.drawImage(renderBuffer, 0, 0, canvas.width, canvas.height); renderBuffer.width = canvas.width; renderBuffer.height = canvas.height; }
function stepTapestry(dt) { const b = buffers.tapestry; const p = state.params.tapestry; const count = Math.max(1, Math.min(5, Math.floor(dt * 60 * (state.reducedMotion ? .2 : .4 + p.scroll * 1.8)))); for (let n = 0; n < count; n += 1) { b.rows[b.cursor] = b.current.slice(); b.current = stepElementary(b.current, p.rule); b.cursor = (b.cursor + 1) % b.rows.length; } }
function drawTapestry() { const b = buffers.tapestry; const p = state.params.tapestry; const image = ctx.createImageData(canvas.width, canvas.height); const a = colorRgb(palette.primary); const s = colorRgb(palette.secondary); const c = colorRgb(palette.accent); for (let y = 0; y < canvas.height; y += 1) { const historyY = Math.floor(y / 5); const offset = p.reversal > .5 ? -Math.floor(state.elapsed * 4 * p.scroll) : Math.floor(state.elapsed * 4 * p.scroll); const rowIndex = (b.cursor - historyY * (1 + Math.floor(p.weave * 2)) + offset + b.rows.length * 20) % b.rows.length; const row = b.rows[rowIndex]; for (let x = 0; x < canvas.width; x += 1) { const col = Math.floor((x / canvas.width) * b.width); const on = row[col]; const weave = Math.sin(x * .028 + y * .011 + state.elapsed * (state.reducedMotion ? .05 : .3)) * .5 + .5; const rgb = on ? mixColor(a, weave > .68 ? c : s, weave) : [4 + Math.floor(weave * 6), 5 + Math.floor(weave * 4), 12 + Math.floor(weave * 12)]; const i = (y * canvas.width + x) * 4; image.data[i] = rgb[0]; image.data[i + 1] = rgb[1]; image.data[i + 2] = rgb[2]; image.data[i + 3] = 255; } } ctx.putImageData(image, 0, 0); }
function stepFeedback() { const p = state.params.feedback; const current = buffers.feedback.current; const next = 1 - current; const source = fctx[current]; const target = fctx[next]; target.setTransform(1, 0, 0, 1, 0, 0); target.globalCompositeOperation = 'source-over'; target.fillStyle = '#04040a'; target.fillRect(0, 0, canvas.width, canvas.height); target.save(); target.translate(canvas.width / 2, canvas.height / 2); target.rotate(p.transform * (state.reducedMotion ? .2 : 1)); target.scale(1 + p.transform * .55, 1 + p.transform * .55); target.translate(-canvas.width / 2, -canvas.height / 2); target.globalAlpha = boundedFeedbackValue(0, 0, p.decay) + boundedFeedbackValue(1, 0, p.decay); target.drawImage(source.canvas, 0, 0); target.restore(); const x = (state.gesture.active ? state.gesture.x : .5 + Math.sin(state.elapsed * .22) * .22) * canvas.width; const y = (state.gesture.active ? state.gesture.y : .5 + Math.cos(state.elapsed * .18) * .22) * canvas.height; const radius = 20 + p.tunnel * 180; const grad = target.createRadialGradient(x, y, 0, x, y, radius); grad.addColorStop(0, `${palette.primary}cc`); grad.addColorStop(.4, `${palette.accent}77`); grad.addColorStop(1, '#0000'); target.globalCompositeOperation = 'lighter'; target.fillStyle = grad; target.beginPath(); target.arc(x, y, radius, 0, Math.PI * 2); target.fill(); const symmetry = Math.round(p.symmetry); for (let n = 1; n < symmetry; n += 1) { target.save(); target.translate(canvas.width / 2, canvas.height / 2); target.rotate((Math.PI * 2 * n) / symmetry); target.translate(-canvas.width / 2, -canvas.height / 2); target.globalAlpha = boundedFeedbackValue(.45, 0, p.decay); target.fillStyle = grad; target.beginPath(); target.arc(x, y, radius * (.72 + n / symmetry * .18), 0, Math.PI * 2); target.fill(); target.restore(); } target.globalCompositeOperation = 'source-over'; buffers.feedback.current = next; state.gesture.active = false; }
function drawFeedback() { ctx.drawImage(fctx[buffers.feedback.current].canvas, 0, 0); }

function stepAndDraw(dt) { if (scene().kind === 'reaction') { stepAcid(dt); drawAcid(); } else if (scene().kind === 'automaton') { stepTapestry(dt); drawTapestry(); } else { stepFeedback(); drawFeedback(); } }
function renderFrame(now) { const dt = Math.min(.05, Math.max(0, (now - state.lastTime) / 1000)); state.lastTime = now; if (!state.paused && !state.blackout) { state.elapsed += dt; updateAudioLevel(); stepAndDraw(dt); metrics.frameTimes.push(dt * 1000); if (metrics.frameTimes.length > 3600) metrics.frameTimes.shift(); metrics.sceneFrames[state.sceneIndex] += 1; } else if (state.blackout) { ctx.fillStyle = '#020207'; ctx.fillRect(0, 0, canvas.width, canvas.height); } if (state.transition) { state.transition.progress = Math.min(1, state.transition.progress + dt / 2.6); ctx.save(); ctx.globalAlpha = 1 - state.transition.progress; ctx.drawImage(transitionCanvas, 0, 0); ctx.restore(); if (state.transition.progress >= 1) state.transition = null; } if (!state.blackout && state.brightness < 1) { ctx.save(); ctx.globalAlpha = 1 - state.brightness; ctx.fillStyle = '#000'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.restore(); } $('fpsReadout').textContent = `${Math.round(1 / Math.max(.001, dt))} FPS · ${state.quality} / ${state.quality === '720' ? '30' : '60'}`; $('transitionBadge').textContent = state.transition ? 'MORPHING' : state.setPlaying ? 'SET LIVE' : 'LIVE'; requestAnimationFrame(renderFrame); }

function updateAudioLevel() { if (!audio.analyser) { state.audioLevel += (0 - state.audioLevel) * .08; } else { audio.analyser.getByteTimeDomainData(audio.data); let sum = 0; for (const value of audio.data) { const n = (value - 128) / 128; sum += n * n; } const next = Math.sqrt(sum / audio.data.length); state.audioLevel += (next - state.audioLevel) * .08; } const mod = clamp(state.audioLevel * 4, 0, 1); $('modulationReadout').textContent = `AUDIO ${Math.round(mod * 100)}%`; if (!state.paused && !state.blackout && mod > .03) { if (scene().kind === 'reaction') state.params.acid.injection = clamp(state.params.acid.injection + (mod * .18 - state.params.acid.injection) * .003, 0, 1); if (scene().kind === 'feedback') state.params.feedback.decay = clamp(state.params.feedback.decay + (mod * .12 - .05) * .002, .72, .99); } }
function stopAudioSource() { if (audio.source) { try { audio.source.stop?.(); } catch {} try { audio.source.disconnect(); } catch {} audio.source = null; } if (audio.demoGain) { try { audio.demoGain.disconnect(); } catch {} audio.demoGain = null; } if (audio.media) { audio.media.pause(); audio.media.removeAttribute('src'); audio.media.load(); audio.media = null; } if (audio.mediaUrl) { URL.revokeObjectURL(audio.mediaUrl); audio.mediaUrl = null; } if (audio.micStream) { audio.micStream.getTracks().forEach((track) => track.stop()); audio.micStream = null; } state.demoOn = false; }
async function ensureAudio() { if (audio.context) { await audio.context.resume(); return; } try { audio.context = new AudioContext(); audio.analyser = audio.context.createAnalyser(); audio.analyser.fftSize = 256; audio.data = new Uint8Array(audio.analyser.fftSize); audio.gain = audio.context.createGain(); audio.gain.gain.value = state.muted ? 0 : .18; audio.recordDestination = audio.context.createMediaStreamDestination(); audio.analyser.connect(audio.gain); audio.gain.connect(audio.context.destination); audio.gain.connect(audio.recordDestination); await audio.context.resume(); $('startAudioButton').textContent = '◉'; showToast('Audio engine ready · local only'); } catch { showToast('Audio could not start in this browser'); } }
async function toggleDemo() { await ensureAudio(); if (!audio.context) return; if (state.demoOn) { stopAudioSource(); $('demoAudioButton').textContent = 'Demo pulse'; showToast('Demo pulse stopped'); return; } stopAudioSource(); const osc = audio.context.createOscillator(); const gain = audio.context.createGain(); osc.type = 'sine'; osc.frequency.value = 110; gain.gain.value = .0001; osc.connect(gain); gain.connect(audio.analyser); osc.start(); const pulse = () => { if (!state.demoOn || !audio.context) return; const t = audio.context.currentTime; gain.gain.cancelScheduledValues(t); gain.gain.setValueAtTime(.0001, t); gain.gain.linearRampToValueAtTime(.12, t + .03); gain.gain.exponentialRampToValueAtTime(.0001, t + .42); setTimeout(pulse, Math.max(200, (60 / state.tempo) * 1000)); }; audio.source = osc; audio.demoGain = gain; state.demoOn = true; $('demoAudioButton').textContent = 'Stop pulse'; pulse(); showToast('Procedural demo pulse engaged'); }
async function loadLocalAudio(file) { if (!file) return; if (file.size > 80 * 1024 * 1024) return showToast('Audio is over the 80 MB local limit'); await ensureAudio(); if (!audio.context) return; stopAudioSource(); const url = URL.createObjectURL(file); const media = new Audio(url); media.loop = true; media.volume = .7; const source = audio.context.createMediaElementSource(media); source.connect(audio.analyser); audio.media = media; audio.mediaUrl = url; audio.source = source; try { await media.play(); showToast(`Local audio loaded · ${file.name}`); } catch { stopAudioSource(); showToast('Local audio playback was blocked · use Demo pulse or manual mode'); } }
async function toggleMic() { await ensureAudio(); if (!audio.context) return; if (audio.micStream) { stopAudioSource(); $('micButton').textContent = 'Mic: off'; return showToast('Microphone released'); } stopAudioSource(); try { audio.micStream = await navigator.mediaDevices.getUserMedia({ audio: true }); const source = audio.context.createMediaStreamSource(audio.micStream); source.connect(audio.analyser); audio.source = source; $('micButton').textContent = 'Mic: on'; showToast('Microphone active · nothing leaves this device'); } catch { $('micButton').textContent = 'Mic: denied'; showToast('Microphone permission denied · manual and demo modes still work'); } }

function startSet() { if (state.setPlaying) { state.setPlaying = false; clearTimeout(cueTimer); $('playSetButton').textContent = '▶ Play set'; state.currentCue = -1; renderCues(); return showToast('Set paused at current scene'); } state.setPlaying = true; $('playSetButton').textContent = 'Ⅱ Pause set'; let index = state.currentCue >= 0 ? state.currentCue : 0; const play = () => { if (!state.setPlaying) return; const cue = cues[index % cues.length]; state.currentCue = index % cues.length; switchScene(cue.scene, cue.preset); renderCues(); const durationMs = cue.duration * 4 * (60 / state.tempo) * 1000; cueTimer = setTimeout(() => { index += 1; play(); }, durationMs); }; play(); showToast('Rehearsed cue set running · 10 transitions remain bounded'); }
function addCue() { cues.push({ label: `${scene().name} / ${preset()[0]}`, scene: state.sceneIndex, preset: state.presetIndex[state.sceneIndex], duration: 8 }); renderCues(); markDirty(); showToast('Cue added to local set'); }

function sessionData() { return { format: 'phosphor-set-v1', version: 1, savedAt: new Date().toISOString(), activeScene: state.sceneIndex, presetIndex: state.presetIndex, params: state.params, palette, tempo: state.tempo, cues, options: { reducedMotion: state.reducedMotion, brightness: state.brightness, quality: state.quality } }; }
let saveTimer = null;
function saveLocal() { try { localStorage.setItem('phosphor-set-v1', JSON.stringify(sessionData())); state.dirty = false; $('dirtyState').textContent = 'SAVED'; $('saveReadout').textContent = 'LOCAL ONLY'; } catch { $('saveReadout').textContent = 'DOWNLOAD'; showToast('Storage is full · use Export JSON for a direct file'); } }
function scheduleSave() { clearTimeout(saveTimer); saveTimer = setTimeout(saveLocal, 450); }
function validateSession(data) { if (!data || data.format !== 'phosphor-set-v1' || data.version !== 1) throw new Error('Unsupported Phosphor set format'); if (!Array.isArray(data.presetIndex) || data.presetIndex.length !== sceneDefs.length) throw new Error('Preset list is malformed'); if (!data.params || !data.params.acid || !data.params.tapestry || !data.params.feedback) throw new Error('Parameter state is missing'); for (const def of sceneDefs) for (const [key, label, min, max] of def.schema) { const raw = Number(data.params[def.id][key]); if (!Number.isFinite(raw) || raw < min || raw > max) throw new Error(`Parameter ${def.id}.${key} is outside its ${min}–${max} bound`); } if (!Array.isArray(data.cues) || data.cues.length < 1 || data.cues.length > 64) throw new Error('Cue list must contain 1–64 cues'); for (const cue of data.cues) if (!Number.isInteger(cue.scene) || cue.scene < 0 || cue.scene >= sceneDefs.length || !Number.isInteger(cue.preset) || cue.preset < 0 || cue.preset >= sceneDefs[cue.scene].presets.length) throw new Error('Cue references an unknown scene'); return data; }
function applySession(data) { const safe = validateSession(data); state.presetIndex = safe.presetIndex.map((n, i) => clamp(Math.round(n), 0, sceneDefs[i].presets.length - 1)); state.params = structuredClone(initialParams); for (const def of sceneDefs) for (const [key] of def.schema) state.params[def.id][key] = clamp(Number(safe.params[def.id][key]), Number(def.schema.find((x) => x[0] === key)[2]), Number(def.schema.find((x) => x[0] === key)[3])); state.tempo = clamp(Number(safe.tempo), 40, 180); if (safe.palette) Object.assign(palette, Object.fromEntries(Object.entries(palette).map(([key, fallback]) => [key, /^#[0-9a-f]{6}$/i.test(safe.palette[key]) ? safe.palette[key] : fallback]))); cues.splice(0, cues.length, ...safe.cues.map((cue) => ({ label: String(cue.label).slice(0, 60), scene: cue.scene, preset: cue.preset, duration: clamp(Number(cue.duration), 1, 64) }))); state.reducedMotion = Boolean(safe.options?.reducedMotion); state.brightness = clamp(Number(safe.options?.brightness ?? .92), .2, 1); state.quality = safe.options?.quality === '720' ? '720' : '1080'; const target = clamp(Number(safe.activeScene), 0, sceneDefs.length - 1); state.sceneIndex = target; fillPalette(); if (scene().kind === 'reaction') resetAcid(); if (scene().kind === 'automaton') resetTapestry(); if (scene().kind === 'feedback') resetFeedback(); renderScenes(); renderControls(); announce(); renderCues(); $('primaryColor').value = palette.primary; $('secondaryColor').value = palette.secondary; $('accentColor').value = palette.accent; $('reducedMotionInput').checked = state.reducedMotion; $('brightnessInput').value = state.brightness * 100; $('qualityInput').value = state.quality; saveLocal(); showToast('Session restored from portable JSON'); }
function download(blob, filename) { const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function exportSession() { download(new Blob([JSON.stringify(sessionData(), null, 2)], { type: 'application/json' }), 'phosphor-set-v1.json'); showToast('Portable set exported'); }
function exportFrameManifest() { const manifest = { format: 'phosphor-frame-sequence-v1', version: 1, width: canvas.width, height: canvas.height, frameRate: state.quality === '720' ? 30 : 60, frames: 120, scene: scene().id, preset: preset()[0], seed: preset()[2], params: state.params[scene().id], palette: { ...palette }, note: 'Render locally from these bounded settings; imported audio remains local and is never embedded.' }; download(new Blob([JSON.stringify(manifest, null, 2)], { type: 'application/json' }), 'phosphor-frame-sequence.json'); showToast('Offline frame manifest exported'); }
function captureStill() { canvas.toBlob((blob) => { if (blob) { download(blob, `phosphor-${scene().id}-${Date.now()}.png`); showToast('Still captured'); } else showToast('Still capture is not available'); }, 'image/png'); }
function finishRecording(saveBlob = false, message = '') { const mime = audio.recordingMime || 'video/webm'; if (saveBlob && audio.chunks.length) download(new Blob(audio.chunks, { type: mime }), `phosphor-${scene().id}-${Date.now()}.webm`); audio.recordingStream?.getTracks().forEach((track) => track.stop()); audio.recordingStream = null; audio.recorder = null; audio.recordingMime = null; audio.chunks = []; $('recordButton').textContent = 'Record'; if (message) showToast(message); }
function toggleRecord() { if (audio.recorder?.state === 'recording') { audio.recorder.stop(); return; } if (!canvas.captureStream || !window.MediaRecorder) return showToast('Recording is unsupported here · use still or frame export'); const videoType = ['video/webm;codecs=vp9,opus', 'video/webm;codecs=vp8,opus', 'video/webm'].find((type) => !MediaRecorder.isTypeSupported || MediaRecorder.isTypeSupported(type)); if (!videoType) return showToast('No supported WebM recorder · use still or frame export'); const stream = canvas.captureStream(state.quality === '720' ? 30 : 60); if (audio.recordDestination) audio.recordDestination.stream.getAudioTracks().forEach((track) => stream.addTrack(track)); audio.recordingStream = stream; audio.recordingMime = videoType; try { audio.recorder = new MediaRecorder(stream, { mimeType: videoType }); } catch { finishRecording(false); return showToast('Recorder setup failed · use still or frame export'); } audio.chunks = []; audio.recorder.ondataavailable = (event) => { if (event.data.size) audio.chunks.push(event.data); }; audio.recorder.onerror = () => finishRecording(false, 'Recording encoder error · capture cleaned up'); audio.recorder.onabort = () => finishRecording(false, 'Recording aborted · capture cleaned up'); audio.recorder.onstop = () => finishRecording(true, 'Local recording saved'); try { audio.recorder.start(); } catch { finishRecording(false, 'Recording could not start · capture cleaned up'); return; } $('recordButton').textContent = 'Stop'; showToast(audio.recordDestination ? 'Recording locally · audio is mixed when a source is active' : 'Recording locally · no upload'); }
function runLifecycleProbe() { const saved = { sceneIndex: state.sceneIndex, presetIndex: [...state.presetIndex], params: structuredClone(state.params), elapsed: state.elapsed }; clearTimeout(saveTimer); state.transition = null; stopAudioSource(); const samples = []; for (let i = 0; i < 10; i += 1) { switchScene((state.sceneIndex + 1) % sceneDefs.length, i % sceneDefs[(state.sceneIndex + 1) % sceneDefs.length].presets.length); if (scene().kind === 'reaction') { stepAcid(.016); drawAcid(); } else if (scene().kind === 'automaton') { stepTapestry(.016); drawTapestry(); } else { stepFeedback(); drawFeedback(); } const pixels = ctx.getImageData(0, 0, 24, 24).data; samples.push({ scene: scene().id, nonBlack: pixels.some((value, index) => index % 4 !== 3 && value > 0), finitePixels: [...pixels].every((value) => Number.isFinite(value)) }); stopAudioSource(); } const result = { switches: samples.length, samples, fixedFeedbackBuffers: buffers.feedback.a.width === canvas.width && buffers.feedback.b.width === canvas.width, fixedTapestryRows: buffers.tapestry.rows.length === 120, fixedAcidCells: buffers.acid.u.length === 9000, audioCleared: !audio.source && !audio.demoGain && !audio.media && !audio.mediaUrl && !audio.micStream, heapDelta: performance.memory ? performance.memory.usedJSHeapSize : null }; state.sceneIndex = saved.sceneIndex; state.presetIndex = saved.presetIndex; state.params = saved.params; state.elapsed = saved.elapsed; if (scene().kind === 'reaction') resetAcid(); if (scene().kind === 'automaton') resetTapestry(); if (scene().kind === 'feedback') resetFeedback(); renderScenes(); renderControls(); announce(); renderCues(); state.dirty = false; $('dirtyState').textContent = 'SAVED'; return result; }

function wire() {
  $('resetButton').addEventListener('click', resetScene); $('randomButton').addEventListener('click', () => { inject(Math.random(), Math.random(), 1); showToast('Growth nudge injected'); }); $('addCueButton').addEventListener('click', addCue); $('playSetButton').addEventListener('click', startSet); $('startAudioButton').addEventListener('click', ensureAudio); $('demoAudioButton').addEventListener('click', toggleDemo); $('micButton').addEventListener('click', toggleMic); $('pauseButton').addEventListener('click', () => { state.paused = !state.paused; $('pauseButton').textContent = state.paused ? 'Resume' : 'Pause'; $('transportState').textContent = state.paused ? 'PAUSED' : 'RUNNING'; }); $('muteButton').addEventListener('click', () => { state.muted = !state.muted; if (audio.gain) audio.gain.gain.value = state.muted ? 0 : .18; $('muteButton').textContent = state.muted ? 'Unmute' : 'Mute'; }); $('tempoInput').addEventListener('input', (event) => { state.tempo = Number(event.target.value); announce(); markDirty(); }); $('captureButton').addEventListener('click', captureStill); $('frameExportButton').addEventListener('click', exportFrameManifest); $('recordButton').addEventListener('click', toggleRecord); $('saveButton').addEventListener('click', () => { saveLocal(); showToast('Set saved locally'); }); $('exportButton').addEventListener('click', exportSession); $('importInput').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file || file.size > 2 * 1024 * 1024) return showToast('Import must be a JSON file under 2 MB'); const reader = new FileReader(); reader.onload = () => { try { applySession(JSON.parse(reader.result)); } catch (error) { showToast(`Import rejected · ${error.message}`); } }; reader.readAsText(file); event.target.value = ''; }); $('audioFileInput').addEventListener('change', (event) => loadLocalAudio(event.target.files[0])); $('primaryColor').addEventListener('input', (event) => { palette.primary = event.target.value; fillPalette(); markDirty(); }); $('secondaryColor').addEventListener('input', (event) => { palette.secondary = event.target.value; fillPalette(); markDirty(); }); $('accentColor').addEventListener('input', (event) => { palette.accent = event.target.value; fillPalette(); markDirty(); }); $('reducedMotionInput').addEventListener('change', (event) => { state.reducedMotion = event.target.checked; markDirty(); }); $('brightnessInput').addEventListener('input', (event) => { state.brightness = Number(event.target.value) / 100; markDirty(); }); $('qualityInput').addEventListener('change', (event) => { state.quality = event.target.value; $('qualityBadge').textContent = `${state.quality} / ${state.quality === '720' ? '30' : '60'}`; markDirty(); }); $('helpButton').addEventListener('click', () => $('helpDialog').showModal()); $('themeButton').addEventListener('click', () => document.body.classList.toggle('high-contrast'));
  canvas.addEventListener('pointerdown', (event) => { const rect = canvas.getBoundingClientRect(); canvas.setPointerCapture(event.pointerId); state.gesture = { x: (event.clientX - rect.left) / rect.width, y: (event.clientY - rect.top) / rect.height, active: true }; inject(); }); canvas.addEventListener('pointermove', (event) => { if (!(event.buttons & 1)) return; const rect = canvas.getBoundingClientRect(); inject((event.clientX - rect.left) / rect.width, (event.clientY - rect.top) / rect.height, .4); }); window.addEventListener('keydown', (event) => { if (event.target.matches('input,button,select')) return; if (event.code === 'Space') { event.preventDefault(); if (state.blackout) { state.blackout = false; $('blackoutLabel').hidden = true; showToast('Blackout recovered'); } else inject(); } if (event.key.toLowerCase() === 'p') $('pauseButton').click(); if (event.key.toLowerCase() === 'b') { state.blackout = !state.blackout; $('blackoutLabel').hidden = !state.blackout; showToast(state.blackout ? 'Blackout engaged' : 'Blackout recovered'); } if (event.key.toLowerCase() === 'r') resetScene(); if (event.shiftKey && event.key === 'ArrowRight') switchScene((state.sceneIndex + 1) % sceneDefs.length); if (event.shiftKey && event.key === 'ArrowLeft') switchScene((state.sceneIndex + sceneDefs.length - 1) % sceneDefs.length); if (/^[1-3]$/.test(event.key)) switchScene(Number(event.key) - 1); });
  window.addEventListener('pagehide', () => { if (audio.recorder) { audio.recorder.onstop = null; audio.recorder.onerror = null; audio.recorder.onabort = null; try { if (audio.recorder.state === 'recording') audio.recorder.stop(); } catch {} finishRecording(false); } stopAudioSource(); });
}

function boot() { const saved = localStorage.getItem('phosphor-set-v1'); if (saved) { try { validateSession(JSON.parse(saved)); } catch { localStorage.removeItem('phosphor-set-v1'); } } resetAcid(); resetTapestry(); resetFeedback(); fillPalette(); renderScenes(); renderControls(); renderCues(); announce(); $('qualityBadge').textContent = '1080 / 60'; wire(); if (saved && localStorage.getItem('phosphor-set-v1')) { try { applySession(JSON.parse(saved)); } catch { showToast('Saved session could not be restored; starting clean'); } } if (new URLSearchParams(location.search).has('probe')) setTimeout(() => { window.__phosphorProbeResult = runLifecycleProbe(); showToast(window.__phosphorProbeResult.samples.every((sample) => sample.finitePixels && sample.nonBlack) && window.__phosphorProbeResult.audioCleared ? 'Lifecycle probe passed' : 'Lifecycle probe found a recovery issue'); }, 350); requestAnimationFrame(renderFrame); }

window.__phosphorTest = { sceneDefs, PHOSPHOR_FAMILY_CATALOG, stepElementary, reactionDiffusionStep, finiteArray, boundedFeedbackValue, lifecycleStressCheck, runLifecycleProbe, sessionData, validateSession };
window.__phosphorMetrics = metrics;
boot();
