// Editorial order of the authored looks, most interesting first (owner
// request 2026-10-09: "beste zuerst"). It decides the catalog order among
// looks with the same rating, so with nothing rated the catalog, the 32
// grid keys and the in-order autopilot walk all start with these.
//
// How it was made: every family got a strength (signature algorithm,
// club impact, how trippy) and its looks a best-first order; a look scores
// strength − 1.5 × its rank inside the family. So the strongest families
// lead, and every family shows its best look early before second looks
// follow. New looks go into this list; a test checks it covers every
// authored look exactly once.
export const CURATED = [
  "mandelbrot:Seahorse Valley",
  "flight:Long Corridor",
  "cathedral:Prismatic Nave",
  "life:Gosper Barrage",
  "flame:Swirl Flame",
  "attractor:Butterfly",
  "tapestry:30 · Wild silk",
  "hyperbolic:Heptagon Weave",
  "quasicrystal:Penrose Rhombs",
  "fourspace:Turning Tesseract",
  "newton:Wada Beads",
  "ripple:Double Slit",
  "mandelbrot:Spiral Tunnel",
  "julia:Seahorse Valley",
  "sandpile:Mandala Bloom",
  "flight:Neon Spiral",
  "voronoi:Honeycomb Relax",
  "beams:Laser Fan",
  "cathedral:Midnight Rose",
  "life:Cyclic Spirals",
  "swarm:Spiral Galaxy",
  "feedback:Prism Descent",
  "flame:Julia Mandala",
  "pulse:Ring Dive",
  "attractor:Aizawa Bloom",
  "interference:Moire Veil",
  "acid:Mycelial City",
  "tapestry:110 · Persistent knots",
  "hyperbolic:Triangle Storm",
  "aquarium:Moon Jellies · Gyre",
  "quasicrystal:Phason Storm",
  "melt:Porcelain Trefoil",
  "fourspace:Twenty-four Cell",
  "magnetic:Storm Loom",
  "newton:Nova Tendrils",
  "ripple:Phased Array",
  "mandelbrot:Minibrot Halo",
  "julia:Dust Filaments",
  "phase:Launch · crossing chorus",
  "sandpile:Identity",
  "flight:Corkscrew",
  "voronoi:Metric Morph",
  "beams:Crossfire",
  "cathedral:Ember Vault",
  "life:Brian's Brain Storm",
  "swarm:Murmuration",
  "feedback:Evolving Tunnel",
  "evolution:Coral Orchard",
  "flame:Kaleido Flame",
  "pulse:Square Tunnel",
  "attractor:Halvorsen Propeller",
  "interference:Orbit Loom",
  "acid:Vein Cathedral",
  "tapestry:90 · Nested linen",
  "hyperbolic:Square Abyss",
  "aquarium:Spore Carnival · Gyre",
  "quasicrystal:Ammann–Beenker",
  "melt:Pearlescent Möbius",
  "fourspace:Duoprism Torus",
  "magnetic:Twin Choir",
  "newton:Halley's Flowers",
  "ripple:Grating Lobes",
  "mandelbrot:Burning Armada",
  "julia:Burning Coast",
  "phase:Launch · long wave",
  "sandpile:Critical Rain",
  "flight:Mine Shaft",
  "voronoi:Power Bubbles",
  "beams:Starburst",
  "cathedral:Opal Reliquary",
  "life:Replicator Field",
  "swarm:Attractor Storm",
  "feedback:Molten Reliquary",
  "evolution:Festival of Buds",
  "flame:Heighway Dragon",
  "pulse:Shard Crown",
  "attractor:Thomas Weave",
  "interference:Petal Resonance",
  "acid:Tidal Membrane",
  "tapestry:30 · Centre column",
  "hyperbolic:Endless Floor",
  "aquarium:Ribbon Grazers · Tide",
  "quasicrystal:Penrose Ribbons",
  "melt:Velvet Woven Orbit",
  "fourspace:Hypercube Close-up",
  "magnetic:Liquid Silk",
  "newton:Wandering Five",
  "ripple:Glass Lens",
  "mandelbrot:Elephant March",
  "julia:Cubic Lace",
  "phase:Gather · domain mosaic",
  "sandpile:Four Crowns",
  "flight:Narrows",
  "voronoi:Delaunay Net",
  "beams:Strobe Fan",
  "cathedral:Brass Procession",
  "life:Glider Rain",
  "swarm:Kick Bloom",
  "feedback:Votive Loom",
  "evolution:Fern Manuscript",
  "flame:Barnsley Fern",
  "pulse:Scanner Bars",
  "attractor:Clifford Dust",
  "interference:Golden Lattice",
  "acid:Lime Bloom",
  "tapestry:150 · Interference lace",
  "hyperbolic:Pentagon Lattice",
  "aquarium:Lantern Shoal · Tide",
  "quasicrystal:Dodecagonal Star",
  "melt:Brushed Figure Eight",
  "fourspace:Sixteen Cell",
  "magnetic:Split Counterpoint",
  "newton:Relaxed Spirals",
  "ripple:Kick Rain",
  "mandelbrot:Filament Lace",
  "julia:Mirror Bloom",
  "phase:Return · after the storm",
  "sandpile:Avalanche Field",
  "flight:Ember Drift",
  "voronoi:Lloyd Storm",
  "beams:Cathedral Haze",
  "cathedral:Enamel Glide",
  "life:Gun & Eater",
  "swarm:Strange Silk",
  "feedback:Quiet Apse",
  "evolution:Pearl Nursery",
  "flame:Spherical Bloom",
  "pulse:Horizon Grid",
  "attractor:Rössler Ribbon",
  "interference:Twin Tides",
  "acid:Night Orchard",
  "tapestry:45 · Chaos fan",
  "hyperbolic:Quiet Disk",
  "aquarium:Glass Twins · Lagoon",
  "quasicrystal:Heptagonal Lace",
  "melt:Foil Ribbon Eclipse",
  "fourspace:Spinning Lattice",
  "magnetic:Breathing Halo",
  "newton:Three Roots",
  "ripple:Grating",
  "mandelbrot:Celtic Braid",
  "julia:Storm Lens",
  "phase:Return · amber islands",
  "sandpile:Kick Sand",
  "voronoi:Concave Stars",
  "beams:Slow Searchlights",
  "cathedral:Enamel Still",
  "life:Methuselah Bloom",
  "swarm:Dust Drift",
  "feedback:Clean Recovery",
  "evolution:Moonroot",
  "flame:Dragon Rose",
  "pulse:Slow Gate",
  "attractor:Inside the Lobe",
  "interference:Crossed Loom",
  "acid:Signal Understory",
  "tapestry:41 · Glider loom",
  "aquarium:Solitary Pearl · Lagoon",
  "quasicrystal:Octagonal Glass",
  "melt:Enamel Still Study",
  "magnetic:Quiet Torus",
  "newton:Nova",
  "ripple:Monsoon",
  "mandelbrot:Ship Rigging",
  "phase:Gather · quiet porcelain",
  "sandpile:Hexagram Drift",
  "voronoi:Taxicab Diamonds",
  "life:Day & Night Lava",
  "evolution:Quiet Herbarium",
  "flame:Sinusoid Weave",
  "attractor:Comet Rain",
  "interference:Bent Horizons",
  "tapestry:184 · Traffic ribbon",
  "quasicrystal:Close Rhombs",
  "newton:Unity Star",
  "ripple:Single Slit",
  "mandelbrot:Cubic Bloom",
  "sandpile:Twin Fountains",
  "voronoi:Chebyshev Blocks",
  "life:313 Vortex",
  "flame:Julia Flame",
  "interference:Ripple Resonance",
  "tapestry:126 · Burning fringe",
  "newton:Under-relaxed Lace",
  "ripple:Dense Lens",
  "mandelbrot:Tricorn Nursery",
  "sandpile:Identity Shapes",
  "voronoi:Laguerre Froth",
  "life:Bosco Bugs",
  "flame:Fern Snowflake",
  "interference:Tempo Veil",
  "tapestry:54 · Twin brocade",
  "ripple:Sonar Rain",
  "sandpile:Grain by Grain",
  "voronoi:Gabriel Lace",
  "life:Primordial Soup",
  "tapestry:73 · Walled gardens",
  "voronoi:Big Cells",
  "life:Wide Spirals",
  "tapestry:102 · Pascal slope",
  "life:Brain Sparks",
  "tapestry:18 · Kink rails",
  "tapestry:22 · Sparse ceremony",
];
