import test from "node:test";
import assert from "node:assert/strict";
import scenes from "../scenes.mjs";
import { migrateLegacy, validateSession, presetSnapshot } from "../session.mjs";

// Portable fields from /tmp/app-core/b-export.json, generated by executing B's
// own sessionData() (app.js:2227), sceneDefs and initialParams on 2026-10-08.
export const bExport = {
  format: "phosphor-set-v1",
  version: 1,
  name: "B fourteen family export",
  activeScene: 0,
  presetIndex: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  params: {
    acid: {
      growth: 0.62,
      injection: 0.34,
      diffusion: 0.82,
      contrast: 1.2,
      drift: 0.25,
    },
    tapestry: { rule: 90, scroll: 0.42, weave: 0.55, reversal: 0, phrase: 8 },
    feedback: {
      decay: 0.91,
      transform: 0.012,
      symmetry: 4,
      injection: 0.55,
      tunnel: 0.58,
    },
    magnetic: {
      attractorX: 0.5,
      attractorY: 0.5,
      attractor: 0.62,
      trail: 0.88,
      density: 0.72,
      motion: 0.54,
      split: 0.35,
    },
    cathedrals: {
      family: 0,
      journey: 0,
      recursion: 4,
      scale: 0.82,
      color: 0.38,
      traversal: 0.44,
      stationary: 0,
      lighting: 0.72,
      material: 0.28,
      fog: 0.3,
      emission: 0.2,
    },
    aquarium: {
      population: 0.56,
      feeding: 0.42,
      trails: 0.84,
      habitat: 1,
      bloom: 0.48,
      food: 0.52,
      extinction: 0.18,
    },
    interference: {
      fieldA: 0.8,
      fieldB: 0.58,
      fieldC: 0.34,
      frequency: 1.4,
      ratio: 0.82,
      phase: 0.36,
      orientation: 0.3,
      filter: 0.72,
      tempoLock: 0.65,
    },
    topology: {
      family: 0,
      loop: 0.62,
      thickness: 0.48,
      twist: 0.58,
      camera: 0.42,
      material: 0.4,
      keyframe: 0.5,
    },
    phase: {
      arc: 0,
      regime: 2,
      compare: 0.5,
      control: 0.48,
      coupling: 0.64,
      disturbance: 0.28,
      release: 0.58,
      tempo: 0.5,
    },
    evolution: {
      mutation: 0.34,
      lock: 0.18,
      lockField: 0,
      generation: 2,
      lineage: 0.5,
      focus: 0.5,
    },
    julia: {
      real: -0.745,
      imaginary: 0.186,
      zoom: 1,
      detail: 64,
      trap: 0.58,
      motion: 0.2,
    },
    fourspace: {
      shape: 0,
      rotation: 0.35,
      counter: 0.23,
      perspective: 0.65,
      density: 24,
      thickness: 0.4,
    },
    hyperbolic: {
      density: 32,
      bend: 0.55,
      orbit: 0.35,
      weave: 0.45,
      thickness: 0.35,
    },
    fractal: {
      cameraSpeed: 0.18,
      steering: 0,
      fractalScale: 2.05,
      detail: 0.62,
    },
  },
  palette: { primary: "#d5ff5f", secondary: "#5364ff", accent: "#ff5bc8" },
  flight: {
    world: "recursive-passages-v1",
    pose: { position: [-0.24, 0.16, -2.1], yaw: 0.28, pitch: 0.12 },
  },
  tempo: 128,
  cues: [
    ["Acid Mycelium", "acid"],
    ["Causal Tapestry", "tapestry"],
    ["Feedback Chapel", "feedback"],
    ["Magnetic Choir", "magnetic"],
    ["Cathedrals of Error", "cathedrals"],
    ["Alien Aquarium", "aquarium"],
    ["Interference Rituals", "interference"],
    ["Topological Melt", "topology"],
    ["Phase Transition Theatre", "phase"],
    ["Evolution Garden", "evolution"],
    ["Julia Observatory", "julia"],
    ["Fourth Dimension", "fourspace"],
    ["Hyperbolic Loom", "hyperbolic"],
    ["Fractal Flight", "fractal"],
  ],
  options: {
    reducedMotion: false,
    brightness: 0.92,
    quality: "1080",
    effects: { symmetry: 0.5, echo: 0.3, chroma: 0.2, glow: 0.4 },
  },
};
bExport.cues = bExport.cues.map(([label, id], scene) => ({
  label,
  scene,
  preset: 0,
  duration: 8,
  sceneParamsSnapshot: structuredClone(bExport.params[id]),
  paletteSnapshot: {
    primary: "#ff0000",
    secondary: "#00ff00",
    accent: "#0000ff",
  },
  effectsSnapshot: { symmetry: 0.5, echo: 0.3, chroma: 0.2, glow: 0.4 },
}));
test("B fourteen-family exports map ten shared families and preserve cue snapshots/palettes", () => {
  const original = structuredClone(bExport);
  const next = migrateLegacy(bExport, scenes);
  assert.equal(next.cues.length, 10);
  assert.deepEqual(
    next.cues.map((cue) => cue.snapshot.scene),
    [
      "acid",
      "tapestry",
      "feedback",
      "magnetic",
      "cathedral",
      "aquarium",
      "interference",
      "melt",
      "phase",
      "evolution",
    ],
  );
  assert.equal(next.tempo, 128);
  assert.equal(next.options.quality, "balanced");
  assert.equal(next.options.echo, 0.3);
  assert.equal(next.options.chroma, 0.2);
  assert.equal(next.cues[1].snapshot.params.scroll, 25); // v2 whole-row grid.
  assert.equal(next.cues[6].snapshot.params.orientation, 54);
  assert.deepEqual(
    next.cues[0].snapshot.palette,
    bExport.cues[0].paletteSnapshot,
  );
  assert.deepEqual(validateSession(next, scenes), next);
  assert.deepEqual(bExport, original);
});
test("R6 B quality tiers preserve approximate resolution and ignore inherited keys", () => {
  for (const [quality, expected] of [
    ["native", "high"],
    ["1080", "balanced"],
    ["720", "low"],
    ["540", "balanced"],
    ["toString", "balanced"],
    [undefined, "balanced"],
  ]) {
    const fixture = structuredClone(bExport);
    fixture.options.quality = quality;
    assert.equal(migrateLegacy(fixture, scenes).options.quality, expected);
  }
});
test("R7 snapshot-less B cues keep their own presets; Evolution uses paramsSnapshot", () => {
  const fixture = structuredClone(bExport);
  fixture.cues = [0, 1, 2].map((preset) => ({
    label: `Magnetic preset ${preset}`,
    scene: 3,
    preset,
    duration: 8,
  }));
  fixture.cues.push({
    label: "Promoted Evolution",
    scene: 9,
    preset: 0,
    duration: 8,
    paramsSnapshot: {
      ...fixture.params.evolution,
      mutation: 0.8,
      generation: 7,
    },
  });
  const original = structuredClone(fixture);
  const migrated = migrateLegacy(fixture, scenes);
  const magnetic = scenes.find((scene) => scene.id === "magnetic");
  for (let preset = 0; preset < 3; preset++)
    assert.deepEqual(
      migrated.cues[preset].snapshot.params,
      presetSnapshot(magnetic, preset).params,
    );
  assert.notDeepEqual(
    migrated.cues[0].snapshot.params,
    migrated.cues[1].snapshot.params,
  );
  assert.ok(Math.abs(migrated.cues[3].snapshot.params.feed - 0.0434) < 1e-12);
  assert.equal(migrated.cues[3].snapshot.params.planting, 10);
  assert.equal(migrated.cues[3].snapshot.params.petals, 0.8);
  assert.deepEqual(fixture, original);
});
