import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app = await readFile(new URL('../app.js', import.meta.url), 'utf8');
const advanced = await readFile(new URL('../advanced.mjs', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const families = [
  ['47', 'acid', 'reaction'], ['51', 'tapestry', 'automaton'], ['52', 'feedback', 'feedback'],
  ['48', 'magnetic', 'particles'], ['49', 'cathedrals', 'geometry'], ['50', 'aquarium', 'aquarium'],
  ['53', 'interference', 'interference'], ['54', 'topology', 'topology'], ['55', 'phase', 'phase'], ['56', 'evolution', 'evolution'],
];

test('all ten families register one shared scene contract', () => {
  for (const [number, id, kind] of families) {
    assert.match(app, new RegExp(`id: '${id}'.*number: '${number}'.*kind: '${kind}'`, 's'), `${number} scene registration`);
    assert.match(app, new RegExp(`id: '${id}'.*presets: \\[([\\s\\S]*?)\\], schema:`, 's'), `${number} authored presets`);
  }
  assert.match(app, /function stepAndDraw\(dt\)[\s\S]*kind === 'evolution'/, 'renderer dispatch');
  assert.match(app, /function resetRenderer\(\)[\s\S]*kind === 'evolution'/, 'reset dispatch');
  assert.match(app, /mechanism: 'Gray–Scott reaction diffusion'/, 'honest mechanism labels');
  assert.match(app, /Start · \$\{item\.presets\[0\]\[0\]\}/, 'authored starting looks');
});

test('new family renderers keep fixed bounded resources in source', () => {
  assert.match(advanced, /precision highp float/, 'Julia has a fragment-shader path');
  assert.match(advanced, /__juliaGpuDisabled/, 'Julia shader failure falls back instead of breaking the stage');
  assert.match(advanced, /function juliaRenderState\(/, 'Julia exposes the selected render path for rehearsal evidence');
  assert.match(advanced, /advancedRasterSize\(width, height, low, options\?\.focus === true\)/, 'Julia Focus can request a bounded higher-detail CPU fallback');
  assert.match(advanced, /juliaGpuSize\(width, height, low, options\?\.focus === true\)/, 'Julia Focus can request a bounded higher-resolution WebGL backing surface');
  assert.match(app, /beatResponseLevel\(scene\(\)\.id\), \{ focus: state\.focusMode \}\)/, 'Julia draw receives the live Focus detail option');
  assert.match(app, /WebGL backing upscale/, 'Focus reports the scale of a supersampled Julia backing surface');
  assert.match(app, /function normalizeQuality\(value\)/, 'quality selection normalizes saved values');
  assert.match(app, /id === '1920x1200' \? 'native'/, 'HD output profile maps through report and frame-plan validation');
  assert.match(html, /<option value="native">HD · 1920×1200 \/ 60 target<\/option>/, 'HD output profile is explicitly opt-in');
  assert.match(app, /magnetic: \{ count: 720, particles: new Float32Array\(720 \* 4\)/, 'Magnetic Choir allocates the HD particle cap');
  assert.match(app, /aquarium: \{ count: 96, organisms: new Float32Array\(96 \* 6\)/, 'Alien Aquarium allocates the HD organism cap');
  assert.match(app, /phase: \{ width: 64, height: 40, values: new Float32Array\(64 \* 40\)/);
  assert.match(app, /Math\.min\(b\.count, Math\.floor\(96 \+ p\.density \* 384\)\)/);
  assert.match(app, /Math\.min\(b\.count, Math\.floor\(4 \+ p\.population \* 60\)\)/);
  assert.match(app, /topologyLoopPoint\(p\.family/);
  assert.match(app, /countPolylineIntersections\(sampled\)/);
  assert.match(app, /keyframes: new Float32Array\(2 \* 5\)/);
  assert.match(app, /drivenRegimeFieldStep\(b\.values/);
  assert.match(app, /b\.compareNext\[index\] = drivenRegimeFieldStep/);
  assert.doesNotMatch(app, /phaseModelNames/);
  assert.match(app, /const phaseModel = \{ id: 'driven-regime-field-v2'/);
  assert.match(app, /const phaseArcs = \[/);
  assert.match(app, /function phaseArcAt\(/);
  assert.match(app, /function startPhaseArc\(/);
  assert.match(app, /function rehearsePhaseArcs\(/);
  assert.match(app, /phaseEvents: state\.phaseEvents/);
  assert.match(app, /phaseMeasurementArchive: state\.phaseMeasurementArchive/);
  assert.match(app, /phaseMeasurement: scene\(\)\.kind === 'phase' \? phaseMeasurement\(\) : null/);
  assert.match(app, /function sanitizePhaseMeasurementArchive\(/);
  assert.match(app, /function frameManifest\(/);
  assert.match(app, /id="capturePhaseMeasurementButton"/);
  assert.match(app, /Saved capture \(archived\)/);
  assert.match(app, /Live current/);
  assert.match(app, /id="playPhaseArcButton"/);
  assert.match(app, /id="rehearsePhaseArcsButton"/);
  assert.match(app, /resolutionAwareInterferenceFilter\(field, neighbors, canvas\.width, canvas\.height, p\.filter\)/);
  assert.match(app, /transitionGap/);
  assert.match(app, /function mutateEvolution\(\)/);
  assert.match(app, /lockedParameters/);
  assert.match(app, /const lockKeys = \['mutation', 'generation', 'lineage', 'focus'\]/);
  assert.match(app, /for \(const key of lockedParameters\) childParams\[key\] = parent\.params\[key\]/);
  assert.match(app, /paramsSnapshot: structuredClone\(node\.params\)/);
  assert.match(app, /evolution: state\.evolution/);
  assert.match(app, /function migrateSession\(data\)/);
  assert.match(app, /const safe = validateSession\(data\); const nextPresetIndex/);
  assert.match(app, /candidate\.presetIndex = \[\.\.\.candidate\.presetIndex, \.\.\.Array\(sceneDefs\.length - candidate\.presetIndex\.length\)\.fill\(0\)\]/);
  assert.match(app, /state\.gesture = \{ x: \.5, y: \.5, active: false, scene: index \}/);
  assert.match(app, /function applyMagneticGesture\(/);
  assert.match(app, /function replayGestureSequence\(/);
  assert.match(app, /gestureHistory: state\.gestureHistory/);
  assert.match(app, /fieldA: \.92/);
  assert.match(app, /const presetConfig = sceneDefs\[index\]\.presets\[nextPreset\]\[3\]/);
  assert.match(app, /switchScene\(cue\.scene, cue\.preset, cue\)/);
  assert.match(app, /nodeId: node\.id, paramsSnapshot: structuredClone\(node\.params\)/);
  assert.match(app, /contextlost/);
  assert.match(app, /contextrestored/);
  assert.match(app, /const visibleSchema = state\.workflow === 'perform'/, 'progressive control modes');
  assert.match(app, /function toggleFocusMode\(/, 'canvas focus mode');
  assert.match(app, /getByteFrequencyData/, 'audio frequency analysis');
  assert.match(app, /import \* as advancedModule from '\.\/advanced\.mjs';/, 'advanced module boundary tolerates older cached exports');
  assert.match(app, /fallbackJuliaRenderState/, 'Julia diagnostics retain a local compatibility fallback');
  assert.match(app, /const audioMappings = \{ acid: \['mid'/, 'scene-specific audio bands');
  assert.match(app, /fractal: \['low', 'detail', \.25\]/, 'Fractal Flight participates in beat modulation');
  assert.match(app, /function scheduleDemoStep\(/, 'demo source schedules a bounded beat pattern');
  assert.match(app, /Dark techno demo beat · kick, clap, hats/, 'demo source names its techno voices');
  assert.match(app, /function playDemoKick\(start, velocity\)[\s\S]*demoOscillator\(start, \.32/, 'demo kick has a dedicated low-end body');
  assert.match(app, /createDynamicsCompressor\?\.\(\)/, 'demo bus uses a bounded compressor when supported');
  assert.match(app, /compressor\.threshold\.value = -18/, 'demo compressor keeps a concrete headroom threshold');
  assert.match(app, /function applyBeatVisualPulse\(/, 'beat pulse reaches every rendered canvas');
  assert.match(app, /const onset = beatVisualArmed && pulse >= beatVisualTriggerThreshold/, 'stage accent follows a hysteresis-gated beat onset rather than sustained energy');
  assert.match(app, /state\.reducedMotion \|\| onset <= \.01/, 'stage accent respects reduced motion and an onset threshold');
  assert.match(app, /state\.demoOn && state\.beatStep % 4 === 0/, 'kick accent is limited to the Demo pattern');
  assert.match(app, /const frameAlpha = clamp\(/, 'beat stage accent keeps a bounded frame alpha');
  assert.match(app, /ctx\.rect\(inset, inset/, 'beat stage accent draws a perimeter cue');
  assert.match(app, /function beatResponseLevel\(/, 'beat envelope feeds scene-specific modulation');
  assert.match(app, /function beatDrivenEffects\(/, 'beat envelope lifts the shared effect stack');
  assert.match(app, /effectStack\.apply\(ctx, beatDrivenEffects\(\), advance\)/, 'beat-driven effects are applied without mutating authored settings');
  assert.match(app, /function visualAudioCoverage\(/, 'beat coverage is inspectable across the scene catalog');
  assert.match(app, /function syncAudioCoverageReadout\(/, 'beat coverage is surfaced in the source dock');
  assert.match(app, /function syncBeatScope\(/, 'per-family beat meters stay synchronized with the source dock');
  assert.match(app, /function syncSceneBeatReadout\(/, 'selected scene exposes its local beat response');
  assert.match(app, /dataset\.selected/, 'beat scope marks the selected visual family');
  assert.match(app, /function syncAudioHeadroomReadout\(/, 'audio peak/headroom is surfaced for rehearsal tuning');
  assert.match(app, /function beatTelemetry\(/, 'beat onset telemetry is versioned and reportable');
  assert.match(app, /function syncRehearsalBeatReadout\(/, 'rehearsal card mirrors onset telemetry');
  assert.match(app, /function recordAudioBeatOnset\(/, 'external audio onsets use a bounded hysteresis gate');
  assert.match(app, /function recordDemoBeatOnset\(/, 'demo steps register at most one onset per 16th note');
  assert.match(app, /function sanitizeBeatTelemetry\(/, 'imported onset telemetry is validated');
  assert.match(html, /id="beatReadout"/, 'beat readout is present in the source dock');
  assert.match(html, /id="audioBeatTelemetryReadout"[^>]*>HITS 0 · LAST —/, 'source dock exposes the onset counter and timestamp');
  assert.match(html, /id="rehearsalBeatReadout"[^>]*aria-live="off"[^>]*>BEAT TELEMETRY · 0 HITS · LAST — · diagnostic only/, 'rehearsal card exposes non-grid onset evidence');
  assert.match(html, /id="sceneBeatReadout"[^>]*role="status"[^>]*>SCENE ACID MYCELIUM · BEAT IDLE/, 'source dock names the selected-scene beat response');
  assert.match(html, /id="audioCoverageReadout"[^>]*>14\/14 VISUALS READY/, 'source dock names complete visual coverage');
  assert.match(html, /id="beatScope"[^>]*role="group"/, 'source dock includes an accessible per-family beat scope');
  assert.match(html, /id="audioHeadroomReadout"[^>]*>PEAK 0% · HEADROOM 100%/, 'source dock starts with explicit headroom');
  assert.match(html, /id="audioRunProgress"[^>]*max="1200"[^>]*value="0"/, 'source dock exposes the bounded sustained audio run target');
  assert.match(app, /progress\.setAttribute\('aria-valuetext'/, 'audio run progress exposes a human-readable elapsed target');
  assert.match(styles, /\.audio-run-progress \{/, 'audio run progress has a bounded source-dock presentation');
  assert.match(app, /data-label-cue/, 'editable cue names');
  assert.match(app, /data-duration-cue/, 'editable cue timing');
  assert.match(app, /data-move-cue/, 'adjacent cue reordering');
  assert.match(app, /data-preview-cue/, 'cue preview recall');
  assert.match(app, /data-duplicate-cue/, 'cue duplication');
  assert.match(app, /name: state\.setName/, 'portable set identity');
  assert.match(app, /function setSetName\(/, 'set name editing');
  assert.match(app, /function exportFilename\(/, 'identity-based export filename');
  assert.match(app, /function assetStem\(/, 'shared identity-based asset stem');
  assert.match(app, /function renderOfflineFramesWithNamedAssets\(/, 'named frame output adapter');
  assert.match(app, /function frameOutputMetadata\(/, 'frame output folders carry a completion manifest');
  assert.match(app, /async writeMetadata\(metadata\)/, 'folder writer persists render completion metadata');
  assert.match(app, /status === 'complete' \? 'All seeded frames were written\.'/s, 'completion metadata distinguishes complete output');
  assert.match(html, /id="setNameInput"/, 'set name editor');
  assert.match(html, /id="readinessReadout"/, 'truthful readiness readout');
  assert.match(app, /function syncReadinessStatus\(/, 'transport/source readiness state');
  assert.match(app, /function stageTransportBadge\(/, 'stage overlay mirrors set transport state');
  assert.match(app, /return state\.transition \? `\$\{transport\} · MORPHING` : transport/, 'stage overlay keeps morphing visible alongside transport');
  assert.match(app, /const next = stageTransportBadge\(\); if \(badge\.textContent !== next\) badge\.textContent = next/, 'stage overlay avoids repeating live-region updates');
  assert.match(html, /id="transitionBadge"[^>]*role="status"[^>]*aria-live="polite"/, 'stage overlay announces transport changes');
  assert.match(app, /SET COMPLETE/, 'completed set readiness state');
  assert.match(app, /Restart set/, 'completed set restart action');
  assert.match(app, /function syncAudioSourceControls\(/, 'recording source lock is surfaced in controls');
  assert.match(app, /function streamTracks\(/, 'native source tracks are read through a guarded helper');
  assert.match(app, /function bindStreamEnded\(/, 'native source teardown watches every track');
  assert.match(app, /Microphone returned no audio · try an audio file/, 'empty microphone streams name a concrete fallback');
  assert.match(app, /No audio was shared · select a browser tab and enable Share tab audio/, 'empty tab streams name a concrete fallback');
  assert.match(app, /aria-pressed.*active/, 'active audio source state is synchronized');
  assert.match(app, /\['demoAudioButton', 'micButton', 'tabAudioButton', 'audioFileInput', 'stopAudioButton'\]/, 'recording locks the stop-source control');
  assert.match(app, /stopAudioButton'\)\.addEventListener\('click', \(\) => \{ if \(!offlineJobActive\(\) && !recordingBlocksSourceChange\(\)\)/, 'stop source handler keeps recording audio intact');
  assert.match(html, /id="demoAudioButton"[^>]*aria-pressed="false"[^>]*aria-describedby="audioStatus beatReadout audioCoverageReadout audioHeadroomReadout(?: audioSessionReadout)?(?: audioBeatTelemetryReadout)?"/, 'demo source announces its state, beat response, coverage, headroom, run, and onset telemetry');
  assert.match(html, /id="audioFileInput"[^>]*aria-describedby="audioStatus beatReadout audioCoverageReadout audioHeadroomReadout(?: audioSessionReadout)?(?: audioBeatTelemetryReadout)?"/, 'file source references its status, beat response, coverage, headroom, run, and onset telemetry');
  assert.match(html, /id="audioOutcomeReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'source outcome is announced');
  assert.match(app, /function syncRecordingReadout\(/, 'recording duration is surfaced while capturing');
  assert.match(app, /try \{ audio\.recorder\.stop\(\); \} catch \{ finishRecording\(false, 'Recording could not stop · capture cleaned up'\); \}/, 'recorder stop failures restore the capture UI');
  assert.match(app, /function recordingMimeType\(/, 'recording capability uses the same MIME probe as capture');
  assert.match(app, /function syncRecordingMimeReadout\(/, 'recording capability exposes the accepted MIME path');
  assert.match(app, /function syncRecordingOutcome\(/, 'recording outcome stays visible after capture');
  assert.match(app, /function bindRecordingStreamEnded\(/, 'capture tracks are watched for an ended recording source');
  assert.match(app, /function setAudioSourceOutcome\(/, 'native source outcomes stay bounded for rehearsal evidence');
  assert.match(app, /function recordAudioSourceEvent\(/, 'native source transitions keep a bounded audit trail');
  assert.match(app, /function syncAudioSourceOutcome\(/, 'native source outcomes stay visible in the source dock');
  assert.match(app, /audio: \{ source: audioSourceKind\(\), status: audioSourceOutcome, history: structuredClone\(audioSourceEvents\)/, 'reports carry the bounded native source outcome history');
  assert.match(app, /sameAudioHistory/, 'rehearsal reports compare source transition history');
  assert.match(app, /sameAudioBeat/, 'rehearsal reports compare captured beat onset telemetry');
  assert.match(app, /function sanitizeRehearsalEnvironment\(/, 'rehearsal reports preserve bounded runtime context');
  assert.match(app, /sameEnvironment/, 'rehearsal reports compare runtime context');
  assert.match(app, /const release = \(\) =>/, 'stale local audio requests have an explicit media cleanup path');
  assert.match(app, /if \(request !== audioRequest\) \{ release\(\); return; \}/, 'stale local audio playback cannot leak its media element');
  assert.match(app, /recordingStatus: recordingOutcome/, 'rehearsal reports carry the bounded recording outcome');
  assert.match(app, /sameRecording/, 'rehearsal reports compare recording outcomes');
  assert.match(app, /recordingMimeType: lastPreflightRecordingMime/, 'rehearsal reports carry the accepted MIME path');
  assert.match(app, /typeof captureCanvas\.captureStream !== 'function'/, 'recording capability requires a callable captureStream');
  assert.match(app, /recording: Boolean\(recordingMimeType\(\)\)/, 'preflight reports actual WebM MIME support');
  assert.match(app, /function syncRecordingMimeReadout\(\) \{[\s\S]*audio\.recordingMime[\s\S]*Active WebM recording path/, 'active recordings expose the MIME path in use');
  assert.match(app, /recordingMimeType: audio\.recordingMime \|\| \(lastPreflightRecordingMime \?\? null\)/, 'rehearsal reports prefer the active recording MIME path');
  assert.match(app, /audio\.recordingStream = stream; audio\.recordingMime = videoType; syncRecordingMimeReadout\(\)/, 'recording start refreshes the active MIME readout');
  assert.match(app, /audio\.recordingMime = null;[\s\S]*syncRecordingMimeReadout\(\); syncAudioSourceControls\(\)/, 'recording cleanup restores the cached MIME readout');
  assert.match(app, /let stream = null;[\s\S]*const clonedTracks = \[\];[\s\S]*Recording capture setup failed/, 'recording capture setup failures are contained and reported');
  assert.match(app, /const tracks = new Set\(\[\.\.\.\(stream\?\.getTracks\?\.\(\) \|\| \[\]\), \.\.\.clonedTracks\]\);[\s\S]*tracks\.forEach\(track => track\?\.stop\?\.\(\)\)/, 'partial capture tracks are stopped on setup failure');
  assert.match(app, /Failed · \$\{job\.written\} PNGs written · use still, WebM, or Frame plan/, 'folder render failure exposes an actionable fallback');
  assert.match(app, /recordingStartedAt: null/, 'recording timing state is explicit');
  assert.match(app, /Microphone ended · choose another source/, 'microphone ending has an actionable fallback');
  assert.match(app, /Shared tab ended · choose another source/, 'tab ending has an actionable fallback');
  assert.match(app, /document\.addEventListener\?\.\('visibilitychange'/, 'hidden-tab recovery listens on the document');
  assert.match(app, /'tabAudioButton', 'stopAudioButton'/, 'offline render locks all source controls');
  assert.match(app, /function updatePerformanceReadout\(/, 'runtime frame health readout');
  assert.match(html, /id="rendererReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'renderer path readout is announced');
  assert.match(html, /id="focusRendererReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'focus mode exposes renderer path');
  assert.match(html, /id="focusPerformanceReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'focus mode exposes frame timing');
  assert.match(html, /id="focusScaleReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'focus mode exposes display scale');
  assert.match(html, /id="focusQualityButton"[^>]*hidden[^>]*>Use HD</, 'focus mode exposes an explicit HD action');
  assert.match(app, /function syncPerformanceReadouts\(/, 'focus mode mirrors frame timing');
  assert.match(app, /function syncFocusScaleReadout\(/, 'focus mode reports CSS display scaling');
  assert.match(app, /function qualityABRendererText\(measurement\)/, 'quality A\/B readout names the actual renderer backing size');
  assert.match(app, /function qualityABRendererAria\(measurement\)/, 'quality A\/B accessibility text names backing-to-output compositing');
  assert.match(app, /function syncFocusQualityAction\(/, 'focus mode synchronizes the HD action');
  assert.match(app, /setQuality\('native'\)/, 'focus HD action selects the native output profile');
  assert.match(styles, /\.focus-quality-button \{ pointer-events:auto;/, 'focus HD action remains clickable inside the pointer-transparent overlay');
  assert.match(app, /function currentRendererEvidence\(/, 'rehearsal reports capture the actual renderer path');
  assert.match(app, /function usableWebglContext\(/, 'preflight probes a usable WebGL context');
  assert.match(app, /CPU fallback .*reason/, 'renderer readout names the fallback reason');
  assert.match(app, /function sanitizeRehearsalRenderer\(/, 'imported renderer evidence is bounded');
  assert.match(app, /sameRenderer/, 'rehearsal reports compare renderer paths');
  assert.match(app, /function performanceTargetSummary\(/, 'runtime frame health compares measured tails to the selected target');
  assert.match(app, /statusLabel: within \? 'Within target' : 'Over target'/, 'runtime frame health keeps target comparison explicit');
  assert.match(app, /const performanceMeasurement = \{ \.\.\.timing, \.\.\.performanceTargetSummary\(timing, profile\) \}/, 'frame plans carry the same target comparison metadata');
  assert.match(app, /const renderStartedAt = performance\.now\(\); stepAndDraw\(renderDt\); const renderDuration = Math\.max\(0, performance\.now\(\) - renderStartedAt\)/, 'frame health measures actual scene rendering');
  assert.match(app, /function resetPerformanceReadout\(/, 'scene changes clear stale frame health');
  assert.match(app, /state\.sceneIndex = index; resetPerformanceReadout\(\)/, 'scene changes reset frame health immediately');
  assert.match(app, /function syncMetricsProfile\(profileId\)[\s\S]*metrics\.reset\(\)/, 'frame health samples are scoped to an output profile');
  assert.match(app, /const p95Index = Math\.min\(sorted\.length - 1, Math\.max\(0, Math\.ceil\(sorted\.length \* \.95\) - 1\)\)/, 'p95 uses a conservative nearest-rank estimator');
  assert.match(html, /id="performanceReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'frame health readout is announced');
  assert.match(app, /'audioSensitivity', 'qualityInput'/, 'offline render locks response sensitivity');
  assert.match(app, /audioCleared: !audio\.source[\s\S]*!audio\.tabStream/, 'lifecycle probe accounts for shared-tab cleanup');
  assert.match(app, /offlineFrameJob = null; setOfflineControlsLocked/, 'offline render clears job before unlocking readiness');
  assert.match(app, /function syncFrameCancelControl\(/, 'offline picker cancel affordance is synchronized');
  assert.match(app, /button\.disabled = Boolean\(job\?\.pickerPending\)/, 'picker pending state disables frame cancellation');
  assert.match(styles, /\.status-line \{ display:flex; flex:1 1 100%; order:3;/, 'mobile readiness visibility');
  assert.match(app, /function preflightReport\(/, 'permission-free rehearsal preflight');
  assert.match(app, /function rehearsalReport\(/, 'rehearsal report captures state without media');
  assert.match(app, /function validateRehearsalReport\(/, 'rehearsal report imports are bounded');
  assert.match(app, /function compareRehearsalReports\(/, 'rehearsal reports can be compared without mutating the set');
  assert.match(app, /function sanitizeRehearsalReportSet\(/, 'rehearsal report transport metadata is bounded');
  assert.match(app, /sameTransport/, 'rehearsal reports compare active transport context');
  assert.match(app, /function readRehearsalReportFile\(/, 'rehearsal report file loader');
  assert.match(app, /function sanitizeRehearsalChecks\(/, 'observed rehearsal checks are validated');
  assert.match(app, /function rehearsalEvidenceStatus\(/, 'observed evidence has an explicit status');
  assert.match(app, /observedEvidence: rehearsalEvidenceStatus\(\)/, 'rehearsal reports carry evidence status');
  assert.match(app, /function syncObservedChecksReadout\(/, 'observed rehearsal check progress is synchronized');
  assert.match(app, /function sanitizeRehearsalChecksAt\(/, 'observed rehearsal checks carry a bounded timestamp');
  assert.match(app, /rehearsalChecksAt: state\.rehearsalChecksAt/, 'portable sessions and reports carry the observed-check timestamp');
  assert.match(app, /function resetObservedChecks\(/, 'observed rehearsal checks can be reset without touching the set');
  assert.match(app, /observedChecks: \{ \.\.\.state\.rehearsalChecks \}/, 'rehearsal reports carry structured observed checks');
  assert.match(app, /rehearsalChecks: \{ \.\.\.state\.rehearsalChecks \}/, 'portable sessions carry structured observed checks');
  assert.match(app, /phosphor-rehearsal-report-v1/, 'rehearsal report has a versioned format');
  assert.match(app, /function exportRehearsalReport\(/, 'rehearsal report export action');
  assert.match(app, /cuePlan: cues\.map/, 'rehearsal report preserves the bounded cue plan');
  assert.match(app, /function markRehearsalReportStale\(\) \{ markRehearsalReportImportStale\(\); if \(offlineFrameJob/, 'saved and loaded reports share stale-state protection');
  assert.match(app, /function markRehearsalReportImportStale\(/, 'loaded rehearsal reports become stale after live changes');
  assert.match(app, /function rehearsalReportStateSignature\(/, 'rehearsal reports compare meaningful live state');
  assert.match(app, /function rehearsalEnvironment\(/, 'rehearsal reports capture coarse runtime context');
  assert.match(app, /function rehearsalReportLiveSignature\(/, 'rehearsal reports use a bounded live freshness signature');
  assert.match(app, /function rehearsalPerformanceSignature\(/, 'rehearsal reports track measured performance freshness separately');
  assert.match(app, /performanceSignature: lastRehearsalReportPerformanceSignature/, 'rehearsal report cache keeps measured performance freshness');
  assert.match(app, /function writeRehearsalReportCache\(/, 'rehearsal reports persist local reopen metadata');
  assert.match(app, /observedChecks: \{ \.\.\.state\.rehearsalChecks \}/, 'rehearsal report cache keeps observed-check metadata');
  assert.match(app, /function restoreRehearsalReportCache\(/, 'rehearsal reports restore local reopen metadata');
  assert.match(app, /environment: rehearsalEnvironment\(\)/, 'rehearsal reports include runtime context');
  assert.match(app, /function sanitizeDeviceLabel\(/, 'rehearsal device labels are bounded');
  assert.match(app, /deviceLabel: state\.deviceLabel/, 'reports and portable sessions carry the named device');
  assert.match(app, /deviceLabel: lastRehearsalReportDeviceLabel/, 'reopened report metadata keeps the captured setup label');
  assert.match(app, /function syncRehearsalReportFreshness\(/, 'rehearsal reports detect transport and readiness drift');
  assert.match(app, /function clearRehearsalReportImport\(/, 'loaded rehearsal reports can be dismissed');
  assert.match(app, /function syncRehearsalReportClearControl\(/, 'loaded-report clear action reflects whether a snapshot is present');
  assert.match(app, /function syncRehearsalReportImportEvidence\(/, 'loaded reports expose captured evidence progress');
  assert.match(app, /clearRehearsalReportButton/, 'loaded-report clear action follows the offline-render lock contract');
  assert.match(app, /function offlineSnapshot\(\) \{ return \{ session:[\s\S]*metricsProfile, frameTimes:/, 'offline rendering snapshots measured metrics before profile changes');
  assert.match(app, /function restoreOfflineSnapshot\(snapshot\) \{ applySession\(snapshot\.session, true\); if \(typeof snapshot\.metricsProfile/, 'offline rendering restores measured metrics after profile changes');
  assert.match(app, /rehearsalReportButton.*tripStackButton/, 'rehearsal report follows the offline-render lock contract');
  assert.match(app, /function localSaveAvailable\(\)[\s\S]*phosphor-preflight-probe-v1/, 'preflight probes local storage writes');
  assert.match(app, /const preflightFallbacks = \{[\s\S]*'Export JSON for a file backup'/, 'preflight includes actionable fallbacks');
  assert.match(app, /class=\"preflight-detail\"/, 'preflight renders fallback guidance');
  assert.match(app, /webglApi: usableWebglContext\(\)/, 'graphics API preflight probes a usable context');
  assert.match(html, /id="preflightButton"/, 'preflight action');
  assert.match(html, /id="rehearsalReportButton"/, 'rehearsal report action');
  assert.match(html, /id="rehearsalReportInput"[^>]*accept="application\/json,.json"/, 'rehearsal report loader');
  assert.match(html, /id="clearRehearsalReportButton"[^>]*disabled/, 'loaded rehearsal report clear action starts disabled');
  assert.match(html, /id="rehearsalReportImportEvidenceReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'loaded report evidence status is announced');
  assert.match(html, /id="rehearsalReportReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'rehearsal report save status');
  assert.match(html, /id="rehearsalReportImportReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'rehearsal report comparison status');
  assert.match(html, /id="recordingMimeReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'recording MIME detail is announced');
  assert.match(html, /id="recordingStatus"[^>]*role="status"[^>]*aria-live="polite"/, 'recording outcome is announced');
  assert.match(html, /id="rehearsalDeviceInput"[^>]*maxlength="80"/, 'bounded device label input');
  assert.match(html, /id="preflightChecklist"/, 'preflight checklist');
  assert.match(html, /id="observedMicCheck"/, 'observed microphone check');
  assert.match(html, /id="observedPerformanceCheck"/, 'observed performance check');
  assert.match(html, /id="observedChecksReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'observed check progress is announced');
  assert.match(html, /id="observedChecksTimestamp"/, 'observed check timestamp is visible');
  assert.match(html, /id="observedChecksNext"/, 'observed check remaining summary');
  assert.match(html, /id="clearObservedChecksButton"/, 'observed check reset action');
  assert.match(styles, /\.observed-checks-readout/, 'observed check progress is visually distinct');
  assert.match(app, /function renderPreflightChecklist\(/, 'preflight detail renderer');
  assert.match(html, /id="preflightTimestamp"/, 'preflight timestamp');
  assert.match(app, /function preflightTimestamp\(/, 'preflight timestamp formatter');
  assert.match(styles, /\.save-row,\.preflight-row,\.set-controls/, 'preflight row uses the shared flex layout');
  assert.match(html, /id="cueCurrentReadout"/, 'current cue readout');
  assert.match(html, /id="cueCurrentReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'current cue readout announces politely');
  assert.match(html, /id="cueList"[^>]*role="list"[^>]*aria-label="Performance cues"/, 'cue list exposes list semantics');
  assert.match(html, /id="saveReadout"[^>]*role="status"[^>]*aria-live="polite"/, 'save freshness is announced');
  assert.match(app, /function flushLocalSave\(\)/, 'page-hide save flush');
  assert.match(app, /role="listitem"[^>]*aria-posinset=/, 'cue rows expose their position');
  assert.match(app, /aria-current=\"step\"/, 'active cue exposes the current step');
  assert.match(app, /function revealCurrentCue\(\)[\s\S]*scrollIntoView/, 'active cue stays visible while the list advances');
  assert.match(html, /id="cueCount">19 CUES<\//, 'static cue count matches the seeded set');
  assert.match(app, /function updateSetProgress\([\s\S]*cueCurrentReadout/, 'named cue progress readout');
  assert.match(app, /function evolutionContour|evolutionContour\(/, 'procedural evolution bodies');
  assert.match(styles, /@media \(min-width:981px\)/, 'desktop split workspace');
  assert.match(styles, /overflow-y:auto/, 'bounded workspace scrolling');
  assert.match(html, /mobile-quickbar/, 'mobile quick actions');
  assert.match(styles, /\.stage-overlay\.top-left \{ top:10px;[\s\S]*\.stage-overlay\.top-right \{ top:10px/, 'narrow stage header separation');
  assert.match(app, /resolutionAwareInterferenceFilter\(field, neighbors, canvas\.width, canvas\.height, p\.filter\)/);
  assert.match(app, /mutation: \.18, lock: 0, lockField: 0, generation: 1/);
  assert.match(app, /resetRenderer\(\); renderScenes\(\); renderControls\(\); announce\(\); renderCues\(\);/);
  assert.doesNotMatch(app, /savedAt:/);
});
